### ISSUE TITLE
crashes with error

### ISSUE THREAD

**Issue by syskey4603** [NisaarAgharia/AI-Shorts-Creator#1]
pytube.exceptions.RegexMatchError: get_throttling_function_name: could not find match for multiple

i would appreciate any help

**Comment by NisaarAgharia** [comment]
this is an older version of code. will be updating the code this week. stay tuned

**Comment by NisaarAgharia** [comment]
we are using pytube to download video from youtube, that has a new bug which you are facing
https://github.com/pytube/pytube/issues/1690
