### ISSUE TITLE
Error with finding gpt-4 model. I have the access to using gpt-4, but am not able to access it.

### ISSUE THREAD

**Issue by Sweetdevil144** [NisaarAgharia/AI-Shorts-Creator#4]
raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist

**Comment by GuilhermeSBlanco** [comment]
having the same issue bro,  did you find out how to fix?

**Comment by GuilhermeSBlanco** [comment]
![image](https://github.com/NisaarAgharia/AI-Shorts-Creator/assets/843673/75042949-2f2b-45c1-8802-4910d7e51945)

**Comment by Sweetdevil144** [comment]
> having the same issue bro, did you find out how to fix?

Not right now but I hope I'll soon find one. I thought using gpt-4-8k would solve the problem but it didn't even bulge and gave this error.
`The model `gpt-4-8k` does not exist`.

Then I tried to increase the token count by using gpt-3.5-turbo-16k which doubled it to 8k tokens.

**Comment by Sweetdevil144** [comment]
I think one possible approach may lie in splitting the video first into multiple segments and then re-examining the videos.
What do you think about this @GuilhermeSBlanco

**Comment by NisaarAgharia** [comment]
The issue is with context length.

The longer the video the bigger the transcripts.

Ideally the transcript should be split in chunks and then processed one by one.

I will be rewriting the code with langchain soon.

If you are getting token limit exceeded try with smaller videos of 5 mins.

I have access to gpt3.5 16k and gpt4 8k.

**Comment by GuilhermeSBlanco** [comment]
do you guys know a way to access gpt4 without paying for it? i'm brazillian and it's kind expansive for me

**Comment by Sweetdevil144** [comment]
> do you guys know a way to access gpt4 without paying for it? i'm brazillian and it's kind expansive for me

No buddy, you can't. You can try gpt-3.5-16k turbo version to increase the token count.
